In [1]:
import cv2
import numpy as np

In [2]:
camera = cv2.VideoCapture(0)

# Functions

In [212]:
def getColors(frame, threshb=127, threshg=127, threshr=127, maxVal=255):
    b,g,r = cv2.split(frame)
    
    b = cv2.threshold(b, threshb, maxVal, cv2.THRESH_BINARY)[1]
    g = cv2.threshold(g, threshg, maxVal, cv2.THRESH_BINARY)[1]
    r = cv2.threshold(r, threshr, maxVal, cv2.THRESH_BINARY)[1]
    
    b[np.where(r == 255) and np.where(g == 0)] = 0
    
    return cv2.merge((b,g,r))

def getCenter(frame):
    y, x, _ = frame.shape
    
    return int(y/2), int(x/2)

def getPortion(frame, portion):
    y, x, _ = frame.shape
    
    return int(y/portion), int(x/portion)

def bincount_app(a):
    a2D = a.reshape(-1,a.shape[-1])
    col_range = (256, 256, 256) # generically : a2D.max(0)+1
    a1D = np.ravel_multi_index(a2D.T, col_range)
    return np.unravel_index(np.bincount(a1D).argmax(), col_range)

In [213]:
while True:
    ret, frame = camera.read()
    cy, cx = getCenter(frame)
    py, px = getPortion(frame, 10)
    
    y1, x1, y2, x2 = cy - int(py/2), cx - int(px/2), cy + int(py/2), cx + int(px/2)
    
    portion = frame[y1:y2, x1:x2]
    
    
    
    colorFrame = getColors(portion)
    cyp, cxp = getCenter(portion)
    print(colorFrame[cyp,cxp])
    
    print(bincount_app(colorFrame))
    
    cv2.rectangle(frame, (cx, cy), (cx, cy), (255,0,0), 4)
    
    cv2.imshow("color Frame", colorFrame)
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1)
    if key == ord("q"):
        cv2.destroyAllWindows()
        break

[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[  0   0 255]
(0, 0, 0)
[  0   0 255]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[  0   0 255]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0, 0, 0)
[0 0 0]
(0

KeyboardInterrupt: 

: 